env: docker
http_server:
  addr: 0.0.0.0:5252
  metrics_addr: ""
filestorage:
  root_dir: /var/lib/coduels/taski
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
db:
  connection_string: host=taski-postgres port=5432 database=taski user=taski password=secret
  init_timeout: 60s
execute:
  endpoint: http://coordinator:5253
  download_task_endpoint: http://taski:5252
event_consumer:
  mode: rest
  brokers: []
  topic: exesh.step-updates
  group_id: taski-e2e
  fetch_interval: 50ms
  rest_endpoint: http://coordinator:5253
  poll_interval: 100ms
  messages_count: 100
  sasl_auth: false
message_dispatcher:
  kafka_enabled: false
  brokers: []
  topic: taski.testing
  sasl_auth: false
metrics_collector:
  collect_interval: 5s
task_topics: []
