networks:
  coduels:
    name: coduels
    driver: bridge
    external: true

volumes:
  postgres:

services:
  postgres:
    image: postgres:17.7
    container_name: taski_postgres
    networks:
      - coduels
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: taski
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taski
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taski"]
      interval: 1s
      timeout: 0s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

  taski:
    build: .
    container_name: taski
    networks:
      - coduels
    ports:
      - "5252:5252"
      - "9077:9090"
    environment:
      CONFIG_PATH: /config/taski.yml
      ENV: docker
      HTTP_SERVER_ADDR: 0.0.0.0:5252
      EXECUTE_ENDPOINT: http://coordinator:5253
      EXECUTE_DOWNLOAD_TASK_ENDPOINT: http://taski:5252
      DB_CONNECTION_STRING: host=taski_postgres port=5432 database=taski user=taski password=secret
      EVENT_CONSUMER_MODE: kafka
      EVENT_CONSUMER_BROKERS: kafka:9092
      MESSAGE_DISPATCHER_KAFKA_BROKERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./file_storage:/app/file_storage
      - ./config:/config:ro
