// <auto-generated />
using System;
using Duely.Infrastructure.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Duely.Infrastructure.DataAccess.EntityFramework.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260628184530_AddedStartDuel")]
    partial class AddedStartDuel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.Duel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Duels", (string)null);

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRated")
                        .HasColumnType("boolean");

                    b.Property<int>("ProblemsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemsOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShouldShowOpponentSolution")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("DuelConfigurations", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelParticipant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DuelId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "DuelId");

                    b.HasIndex("DuelId");

                    b.ToTable("DuelParticipants", (string)null);

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelProblem", b =>
                {
                    b.Property<int>("DuelId")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("DuelId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("DuelProblems", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalSystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemName", "ExternalId")
                        .IsUnique();

                    b.ToTable("Problems", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.RankedDuelSearcher", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.ToTable("RankedDuelSearchers", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdentityTicket")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityTicket")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Duely.Infrastructure.IntegrationEvents.Models.IntegrationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NextProcessAttemptAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProcessAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("IntegrationEvents", (string)null);

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.Duels.RankedDuel", b =>
                {
                    b.HasBaseType("Duely.Domain.Models.Duels.Entities.Duel");

                    b.HasDiscriminator().HasValue("Ranked");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelParticipants.RankedDuelParticipant", b =>
                {
                    b.HasBaseType("Duely.Domain.Models.Duels.Entities.DuelParticipant");

                    b.Property<int>("InitialRating")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Ranked");
                });

            modelBuilder.Entity("Duely.Infrastructure.IntegrationEvents.Models.SendMessageIntegrationEvent", b =>
                {
                    b.HasBaseType("Duely.Infrastructure.IntegrationEvents.Models.IntegrationEvent");

                    b.Property<TimeSpan>("ExpirationTime")
                        .HasColumnType("interval");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("SendMessage");
                });

            modelBuilder.Entity("Duely.Infrastructure.IntegrationEvents.Models.StartDuelIntegrationEvent", b =>
                {
                    b.HasBaseType("Duely.Infrastructure.IntegrationEvents.Models.IntegrationEvent");

                    b.Property<int>("DuelId")
                        .HasColumnType("integer");

                    b.HasIndex("DuelId");

                    b.HasDiscriminator().HasValue("StartDuel");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.Duel", b =>
                {
                    b.HasOne("Duely.Domain.Models.Duels.Entities.DuelConfiguration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelConfiguration", b =>
                {
                    b.HasOne("Duely.Domain.Models.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelParticipant", b =>
                {
                    b.HasOne("Duely.Domain.Models.Duels.Entities.Duel", "Duel")
                        .WithMany("Participants")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duely.Domain.Models.Users.Entities.User", "User")
                        .WithMany("DuelsParticipation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.DuelProblem", b =>
                {
                    b.HasOne("Duely.Domain.Models.Duels.Entities.Duel", "Duel")
                        .WithMany("Problems")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duely.Domain.Models.Duels.Entities.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duel");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.RankedDuelSearcher", b =>
                {
                    b.HasOne("Duely.Domain.Models.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Duely.Infrastructure.IntegrationEvents.Models.SendMessageIntegrationEvent", b =>
                {
                    b.HasOne("Duely.Domain.Models.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duely.Infrastructure.IntegrationEvents.Models.StartDuelIntegrationEvent", b =>
                {
                    b.HasOne("Duely.Domain.Models.Duels.Entities.Duel", null)
                        .WithMany()
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duely.Domain.Models.Duels.Entities.Duel", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("Duely.Domain.Models.Users.Entities.User", b =>
                {
                    b.Navigation("DuelsParticipation");
                });
#pragma warning restore 612, 618
        }
    }
}
