// <auto-generated />
using System;
using Duely.Infrastructure.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Duely.Infrastructure.DataAccess.EntityFramework.Migrations
{
    [DbContext(typeof(Context))]
    partial class UnitOfWorkModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Duely.Domain.Models.Duel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("EndTime");

                    b.Property<int>("MaxDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("MaxDuration");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Result");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaskId");

                    b.Property<int>("User1Id")
                        .HasColumnType("integer")
                        .HasColumnName("User1Id");

                    b.Property<int>("User2Id")
                        .HasColumnType("integer")
                        .HasColumnName("User2Id");

                    b.HasKey("Id");

                    b.ToTable("Duel", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<int>("DuelId")
                        .HasColumnType("integer")
                        .HasColumnName("DuelId");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("SubmitTime");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.Property<string>("Verdict")
                        .HasColumnType("text")
                        .HasColumnName("Verdict");

                    b.HasKey("Id");

                    b.HasIndex("DuelId");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("Duely.Domain.Models.Submission", b =>
                {
                    b.HasOne("Duely.Domain.Models.Duel", "Duel")
                        .WithMany()
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duel");
                });
#pragma warning restore 612, 618
        }
    }
}
