env: dev
http_server:
  addr: 0.0.0.0:5253
  metrics_addr: 0.0.0.0:9090
storage:
  connection_string: host=exesh_postgres port=5432 database=exesh user=coordinator password=secret
  init_timeout: 60s
filestorage:
  root_dir: file_storage/coordinator
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
job_factory:
  output:
    compiled_binary: bin
    run_output: output
  source_ttl:
    filestorage_bucket: 30m
  filestorage_endpoint: http://coordinator:5253
execution_scheduler:
  executions_interval: 500ms
  capacity: 7680000000 # 10000 milliseconds * 512 megabytes * 300 tests * 5 executions
  execution_retry_after: 30s
job_scheduler:
  promised_jobs_limit: 5
  promise_reschedule_interval: 100ms
  metrics_retention: 5m
  metrics_max_finished_jobs: 10000
worker_pool:
  worker_die_after: 1s
dispatcher:
  kafka_enabled: true
  brokers:
    - kafka:9092
  topic: exesh.step-updates
  sasl_auth: false
