env: dev
http_server:
  addr: localhost:5252
  metrics_addr: 0.0.0.0:9090
filestorage:
  root_dir: file_storage
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
db:
  connection_string: host=localhost port=5434 database=taski user=taski password=secret
  init_timeout: 5m
execute:
  endpoint: http://localhost:5253
  download_task_endpoint: http://localhost:5252
event_consumer:
  mode: kafka
  brokers:
    - 0.0.0.0:29092
  topic: exesh.step-updates
  group_id: taski
  fetch_interval: 50ms
  rest_endpoint: http://localhost:5253
  poll_interval: 250ms
  messages_count: 100
  sasl_auth: false
message_dispatcher:
  kafka_enabled: true
  brokers:
    - 0.0.0.0:29092
  topic: taski.testing
  sasl_auth: false
metrics_collector:
  collect_interval: 5s
tasks:
  - 7d971f50363cf0aebbd87d971f50363cf0aebbd8
  - 0c5fe950363fc0aeb7d80c5fe950363fc0aeb7d8
  - 8dedebf10e8b832aedb0a972b6491aa30ea34717
  - 52804c4253a0e5f27594db1f1995efb8f6f64cc2
  - 6620e324f67fefe6d7ec98e341570430f35cc114
  - 95ed43c4d0a2294df1b5b1545c1b59e5d057afa5
  - bfee6b51ab27caec7a10e3fa7d4d831d0a7ea3ab
  - 5de38a1d2f608a513cc19e95a15f71e0a9a7d707
  - 224d5bff6b9f8d8ea999587f5a691f38377cb861
  - ebf8afb29a7596b3e7b46f64089c3b6ff900402d
  - 64ae68ea98ef97e2b43940ef37c4b76248537cc7
  - 8525aaa8359e52b9251c3d249c0cad272acd6251
task_topics:
  - структуры данных
  - дерево отрезков