- name: Deploy
  hosts: Production
  vars_files:
    - credentials.yml
  remote_user: root
  tasks:
    - name: Ensure network exists
      docker_network:
        name: coduels
        state: present
    - name: Pull coordinator image
      docker_image:
        name: divancode74/coduels-exesh
        tag: "{{ version }}"
        source: pull
        force_source: true
    - name: Pull dashboard image
      docker_image:
        name: divancode74/coduels-exesh-dashboard
        tag: "{{ version }}"
        source: pull
        force_source: true
    - name: Run coordinator container
      docker_container:
        name: coordinator
        image: "divancode74/coduels-exesh:{{ version }}"
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        ports:
          - "5253:5253"
          - "9080:9090"
        command:
          - /app/bin/coordinator
        env:
          ENV: prod
          CONFIG_PATH: /app/config/coordinator.yml
          STORAGE_CONNECTION_STRING: "{{ coordinator_postgres_connection }}"
          HTTP_SERVER_ADDR: 0.0.0.0:5253
          HTTP_SERVER_METRICS_ADDR: 0.0.0.0:9090
          JOB_FACTORY_FILESTORAGE_ENDPOINT: http://coordinator:5253
          DISPATCHER_KAFKA_ENABLED: "true"
          DISPATCHER_BROKERS: "192.168.0.6:19092"
          DISPATCHER_SASL_AUTH: "true"
          DISPATCHER_SASL_USERNAME: coordinator
          DISPATCHER_SASL_PASSWORD: "{{ kafka_password }}"
        networks:
          - name: coduels
    - name: Run worker-1 container
      docker_container:
        name: worker-1
        image: "divancode74/coduels-exesh:{{ version }}"
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        ports:
          - "5254:5254"
          - "9081:9091"
        command:
          - /app/bin/worker
        privileged: true
        env:
          ENV: prod
          CONFIG_PATH: /app/config/worker.yml
          HTTP_SERVER_ADDR: 0.0.0.0:5254
          HTTP_SERVER_METRICS_ADDR: 0.0.0.0:9091
          FILE_STORAGE_ROOT_DIR: file_storage/worker-1
          WORKER_ID: http://worker-1:5254
          WORKER_FREE_SLOTS: "4"
          WORKER_AVAILABLE_MEMORY_MB: "2048"
          WORKER_COORDINATOR_ENDPOINT: http://coordinator:5253
        networks:
          - name: coduels
    - name: Run worker-2 container
      docker_container:
        name: worker-2
        image: "divancode74/coduels-exesh:{{ version }}"
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        ports:
          - "5255:5255"
          - "9082:9092"
        command:
          - /app/bin/worker
        privileged: true
        env:
          ENV: prod
          CONFIG_PATH: /app/config/worker.yml
          HTTP_SERVER_ADDR: 0.0.0.0:5255
          HTTP_SERVER_METRICS_ADDR: 0.0.0.0:9092
          FILE_STORAGE_ROOT_DIR: file_storage/worker-2
          WORKER_ID: http://worker-2:5255
          WORKER_FREE_SLOTS: "4"
          WORKER_AVAILABLE_MEMORY_MB: "2048"
          WORKER_COORDINATOR_ENDPOINT: http://coordinator:5253
        networks:
          - name: coduels
    - name: Run dashboard container
      docker_container:
        name: exesh-dashboard
        image: "divancode74/coduels-exesh-dashboard:{{ version }}"
        recreate: yes
        restart: yes
        restart_policy: unless-stopped
        ports:
          - "9000:9000"
        env:
          EXESH_DASHBOARD_DB_CONNECTION_STRING: "{{ dashboard_postgres_connection }}"
        networks:
          - name: coduels
