name: Duely

on:
  pull_request:
    branches:
      - master
    paths:
      - Duely/**
      - .github/workflows/duely_pull_request.yml

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build .NET project
        run: |
          cd Duely
          dotnet build --configuration Release