name: Exesh

on:
  pull_request:
    branches:
      - master
    paths:
      - Exesh/**
      - nginx/**
      - .github/workflows/exesh_pull_request.yml

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.24.0"
      - name: Run tests
        run: |
          cd Exesh
          go test -v ./...
      - name: Check dashboard
        run: |
          cd Exesh/dashboard
          python -m pip install -r requirements.txt
          python manage.py check
