name: Taski

on:
  pull_request:
    branches:
      - master
    paths:
      - Taski/**
      - "!Taski/tasks"
      - .github/workflows/taski_pull_request.yml

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.24.0"
      - name: Run tests
        run: |
          cd Taski
          go test -v ./...